### ISSUE TITLE
doc is quite confusing and needs cleanups

### ISSUE THREAD

**Issue by oyeyipowale** [ehooo/django_mqtt#12]

**Comment by ehooo** [comment]
Could you provide some example or information about what/where is the confusion

**Comment by oyeyipowale** [comment]
Sorry, But I just can wrap my head around most of the documentation's instructions. Looks mashed up.
for example, I have no idea what is going here. Is there some kind of typo? 

https://github.com/ehooo/django_mqtt#how-user-for-publish-data-con-mqtt-server-

if you see no issue with it. No problem. thanks

**Comment by ehooo** [comment]
Hi @oyeyipowale I wrote the doc, so for me is clear, however, I'm not a partial user xD so let me know what is the problem, and I could rewrite cleared the doc.

The information that you send to MQTT is the object Data, in order to send that information you must configure it with the Server (host), the Client (config) and the Topic (where the data will be sent).

Because the Data object could be used for send and receive information (see [how-to-update-data-from-remote-mqtt](https://github.com/ehooo/django_mqtt#how-to-update-data-from-remote-mqtt)) in case that you want send the information you must call to update_remote function.
